dist: trusty

sudo: required

language: bash

before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash

install:
- sudo pip install -r ansible/requirements.txt
- sudo curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip && unzip tflint.zip && sudo cp tflint /usr/sbin
- sudo pip install ansible-lint
#- sudo wget https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_freebsd_amd64.zip -O /tmp/terraform.zip && sudo unzip -o /tmp/terraform.zip -d /usr/sbin/
#- sudo wget https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_freebsd_amd64.zip -O /tmp/terraform2.zip && sudo unzip /tmp/terraform2.zip
- wget https://releases.hashicorp.com/terraform/0.12.19/terraform_0.12.19_linux_amd64.zip -O /tmp/terraform.zip
- sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

script:
- packer validate -var-file=packer/variables.json.example packer/app.json
- packer validate -var-file=packer/variables.json.example packer/db.json
- tflint terraform/stage
- tflint terraform/prod
- cd terraform/prod && terraform init -backend=false && terraform validate && cd ..
- pwd
- ls -la
- cd stage && terraform init -backend=false && terraform validate && cd ..
- ansible-lint ansible/playbooks

branches:
  only:
  - master
  - ansible-3

notifications:
  slack:
    rooms:
      secure: k8G66YuWZDuWJw8o2fG5uT5EliVQ4xrnk4WRvbttcF4MV/MF2LjAWJrpmJSKSPwycV2qF04iCwuYxz1R3OcRer+hhwf3YolJ+pOWsxgvfKXXbTena8Luf46WWaCP3tkirPZ3F3aROQaRZlvwzMdDALmyS81NFhtzYTHTZ/hy75Vvc1Fo2giDh0QJOb4yJYRdewzKvRK9ZZoEiMrIJImyOHn0RQx22kLGOOSIEC+CNd7mhkcrYvhJKkIGRjLgkbfWLVomPB3eUGR0fwmXXMKy8nRe4rBYdjii9JamE+lwyTcRH6+tR/sg+v3PqQqcbMGZ+xI7ZAcfwAnCfbQFmzpD4L1AH5D0FYZnxmRuSDdB+g5hd/Dj155V8BXIQlA7iWdc+C/kP0fS0Wr1sah3ekWeFXftx30zy90YWOVs7j+lVdZ+190W5bJrpVBvFa+dbyzG/TCbqLvRDka0RQLLrMN9472+ynyN8PPG4pbogdBhslTqpG7GrrVIjpKRtNtQV6q+JSy8MV3oD6oK6xr1FyH4mSoQ1jOxIvKqCDmkcNjQeNU9Z+MZ9PCR4qMgBtfgowCN1/aXolec+KowPwKcaulkrXJyLrNF3AIUV1XtrStuXeS8WmVhricrYPIbwmz85QndSPosMcc9BRgORElxTpCtJe823bPHMhyFoJkRahm5sJQ=
